hostapd: fixed compilation warnings
Below warnings are fixed:

1) ../src/rsn_supp/wpa.c:2693:12: error: 'wpa_key_mgmt_suite' defined
   but not used [-Werror=unused-function]
   static u32 wpa_key_mgmt_suite(struct wpa_sm *sm)
2) ../src/ap/wpa_auth.c:4449:21: error: 'wpa_bool_txt' defined but not
   used [-Werror=unused-function]
   static const char * wpa_bool_txt(int val)
3) Uninitialized warning has been fixed

Signed-off-by: Karthikeyan Kathirvel <kathirve@codeaurora.org>
Change-Id: I662d641a5f1a7bce60b9aa8477131f6c8d27dd33