hostapd: Enable hostap-macsec for target ipq50xx
1) enable hostapd-macsec and wpa_supplicant-macsec for ipq50xx

2) fix below compile issue:

../src/ap/wpa_auth.c:79:18: error: 'dot11RSNAConfigSATimeout' defined
but not used [-Werror=unused-const-variable=]
 static const int dot11RSNAConfigSATimeout = 60;
                  ^~~~~~~~~~~~~~~~~~~~~~~~
../src/ap/wpa_auth.c:78:18: error: 'dot11RSNAConfigPMKReauthThreshold'
defined but not used [-Werror=unused-const-variable=]
 static const int dot11RSNAConfigPMKReauthThreshold = 70;

Change-Id: Iaef57d5ce330b8db12c3a71924cdfa1dbb1e1c4c
Signed-off-by: leiwei <leiwei@codeaurora.org>