hostapd: fix int-in-bool-context Werror
Add changes to fix the below compilation error.

./src/rsn_supp/wpa.c:621:35: error: ?: using integer constants
in boolean context, the expression will always evaluate
to 'true' [-Werror=int-in-bool-context]

Signed-off-by: Abinaya Kalaiselvan <akalaise@codeaurora.org>
Change-Id: I7a899a5fec700bd126b883526787b1df808929c5