hostapd: fix compilation issues
Below warnings are fixed
1) ctrl_iface.c:3296:3: error: implicit declaration of function
'hostapd_remove_acl_mac' [-Werror=implicit-function-declaration]
   hostapd_remove_acl_mac(acl, num, (*acl)[0].addr);
      ^
2) driver_nl80211_event.c:2621:24: error: format '%lx' expects argument
of type 'long unsigned int', but argument 3 has type 'u64 {aka long long
    unsigned int}' [-Werror=format=]
      wpa_printf(MSG_DEBUG, "nl80211: BSS color collision - bitmap
	      %08lx",
3) ctrl_iface.c:1441:47: error: suggest parentheses around arithmetic in
      operand of '|' [-Werror=parentheses]
           hapd->iface->conf->he_mu_edca.he_qos_info & 0xf0 |
4) ../src/drivers/driver_nl80211.c:4347:6: error: unused variable 'ret'
	[-Werror=unused-variable]
	  int ret;
	        ^
5) ../src/drivers/driver_nl80211.c: In function
	'nl80211_unsol_bcast_probe_resp':
	../src/drivers/driver_nl80211.c:4402:6: error: unused variable
	'ret' [-Werror=unused-variable]
	  int ret;
	        ^
6) ../src/crypto/sha1-internal.c:144:0: error: "R0" redefined [-Werror]
 #define R0(v,w,x,y,z,i) \

Signed-off-by: Karthikeyan Kathirvel <kathirve@codeaurora.org>
Change-Id: I540fa07363a554e1cfa6f125d32cce42de47d601