hostapd: fixed compilation warnings
Below warnings are fixed:

1) ../src/drivers/driver_nl80211.c:4307:34: error:
  unused variable 'drv' [-Werror=unused-variable]
  struct wpa_driver_nl80211_data *drv = bss->drv;
                                  ^
2) ../src/drivers/driver_nl80211.c:4344:34: error:
  unused variable 'drv' [-Werror=unused-variable]
  struct wpa_driver_nl80211_data *drv = bss->drv;
                                  ^
3) ../src/ap/beacon.c:1295:20: error: unused variable
  'cap_info' [-Werror=unused-variable]
  u16 frm_cntl = 0, cap_info = 0, rsn_cap = 0;
                    ^
4) ../src/ap/beacon.c:1294:24: error: unused variable
  'nss' [-Werror=unused-variable]
  u8 *pos, *length_pos, nss = 0, rsn = 0, buf[200], buf_len;

Signed-off-by: Karthikeyan Kathirvel <kathirve@codeaurora.org>
Change-Id: If163f5fdb972b7c74938751f9a1d7cbcedc95f93